# The URL the site will be built for
base_url = "https://dragonwolfsp.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "anemone"
title = "The Den of the Animmyrath"
author = "Animmyrath(Ethan Jones legally.)"
feed_filenames = ["rss.xml"]
taxonomies = [
    { name = "genres", paginate_by = 10},
]


[markdown]
smart_punctuation = true
render_emoji = true

[extra]
twitter_card = false
header_nav = [
    { url = "/", name_en = "home" },
    { url = "/software", name_en = "software" },
    { url = "/soundschemes", name_en = "sound schemes" },
    { url = "/services", name_en = "services" },
    { url = "/resume", name_en = "resume"},
    { url = "/blog", name_en = "blog" },
    { url = "/journal", name_en = "journal" },
    { url = "/music", name_en = "music" },
    { url = "/buttons", name_en = "buttons" },
    { url = "/social", name_en = "social media" },
    { url = "/about", name_en = "about" },
    { url = "//status.dragonwolfsp.com", name_en = "status" },
    { url = "/credits", name_en = "credits" }
]
footer_content_license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
footer_content_license_link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
copy_year = "2026"
favicon = "graphics/dragonwolf.ico"

